title = "Swisspinball"
baseURL = "https://swisspinball.ch/"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"
copyright = "Swisspinball"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.de]
    title = "Schweizer Flipper Turniere"
    weight = 1
    contentDir = "content/de"
  [languages.fr]
    title = "Tournois de flipper suisse"
    weight = 2
    contentDir = "content/fr"
  [languages.en]
    title = "Swiss Pinball Tournaments"
    weight = 3
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  site_logo = "/images/Swisspinball-Logo.png"
  author = ""
  favicon = "/images/favicon.ico"
  text_color = ""
  description = "Swiss Pinball Tournaments At A Glance"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-red"
  recent_posts_number = 3
